# ========================
# PostgreSQL Configuration
# ========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgre_user
quarkus.datasource.password=postgre_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/postgre_db?currentSchema=payment_schema
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# ========================
# Kafka Producer Configuration
# ========================
mp.messaging.outgoing.my-producer.connector=smallrye-kafka
mp.messaging.outgoing.my-producer.topic=my-kafka-topic
mp.messaging.outgoing.my-producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.my-producer.bootstrap.servers=localhost:9092

# ========================
# Kafka Consumer Configuration
# ========================
mp.messaging.incoming.my-kafka-topic.connector=smallrye-kafka
mp.messaging.incoming.my-kafka-topic.topic=my-kafka-topic
mp.messaging.incoming.my-kafka-topic.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.my-kafka-topic.bootstrap.servers=localhost:9092
mp.messaging.incoming.my-kafka-topic.auto.offset.reset=earliest

# ========================
# HTTP Port Configuration
# ========================
quarkus.http.port=8003
