quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgre_user
quarkus.datasource.password=postgre_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/postgre_db?currentSchema=payment_schema

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.max-size=16

quarkus.http.port=8003
